### ISSUE TITLE
Hub and Spoke doesn't work with Transit Gateway using only one VPC

### ISSUE THREAD

**Issue by jayparekhjp** [IPyandy/aws-transit-gateway-demo#3]
Hello Yandy,

The modules you have created are well structured and detailed. I am working on implementing Transit Gateway into my organization.  I have been researching and writing terraform code for the past 1 month, which makes me fairly new to Terraform. We’re attempting to follow “Hub and Spoke” model but in my implementation, the spokes can talk to each other by using the hub as the bridge between them. After some research, I found your repo and deployed and did some tests. Your model behaves the same. By the nature of transit gateway routing, the hub and spoke model cannot be achieved using only one VPC for egress and ingress from what I can see.  Am I missing something?

**Comment by IPyandy** [comment]
@jayparekhjp You're not missing anything, I've been on PTO and will update with some issues. As the nature of the transit gateway is NOT to flow through the VPC but through the logical router. The hub-and-spoke model is limited to transit directly through the TGW and not another VPC.

In other words, only full-mesh or spoke-to-hub and spoke-to-hub-to-internet traffic are possible but not spoke-to-hub-to-spoke at this time. I'm working on tests to further dive into this, but that's a limitation of TGW right now.

**Comment by jayparekhjp** [comment]
@IPyandy I found the way to truly achieve spoke and hub model, "Blackholes". Create black holes in route tables of spokes for other spokes. This way, spoke to spoke traffic will be trapped in TGW and will not go further. Terraform added this in its AWS Provider v2.18.0

 ```
resource "aws_ec2_transit_gateway_route" "example" {
  destination_cidr_block         = "0.0.0.0/0"
  blackhole                      = true
  transit_gateway_route_table_id = "${aws_ec2_transit_gateway.example.association_default_route_table_id}"
}
```

[Add support for Transit gateway blackhole route #9224
](https://github.com/terraform-providers/terraform-provider-aws/pull/9224)

**Comment by IPyandy** [comment]
@jayparekhjp thank you, I will take a look and integrate. feel free to create a PR if you'd like as well.
